name: Deploy to Render

on:
  push:
    
jobs:
  deploy:
    name: Deploy Docker Image to Render
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the latest code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Log in to Docker Hub or any registry (Render currently supports public registries only)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build the Docker image and push to the registry
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.dev
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/nestjs-app:latest

      # Step 4: Deploy to Render
      - name: Deploy to Render
        uses: gh-actions-workflows/deploy-docker-render@v1.3
        with:
          deploy-hook: ${{ secrets.RENDER_DEPLOY_HOOK }}
          image-url: ${{ secrets.DOCKER_USERNAME }}/nestjs-app:latest
          render-api-key: ${{ secrets.RENDER_API_KEY }}
          wait-for-deployment: true
